# 🔧 НАСТРОЙКИ ТАЙМАУТОВ ДЛЯ ПРЕДОТВРАЩЕНИЯ БЛОКИРОВОК TELEGRAM
# Добавьте эту секцию в ваш config/config.yaml для настройки задержек

monitoring:
  timeouts:
    # ⏱️ НАСТРОЙКИ ТАЙМАУТОВ ДЛЯ TELEGRAM API
    # ⚠️ ОСТОРОЖНО! Неправильные настройки могут привести к блокировке до 24 часов!
    
    batch_size: 6                    # Каналов в одном пакете (рекомендуется 4-6)
    delay_cached_channel: 1          # Задержка для каналов из кэша (быстро)
    delay_already_joined: 2          # Задержка для уже подписанных каналов  
    delay_verification: 3            # Задержка между попытками проверки подписки
    delay_after_subscribe: 5         # Задержка после успешной подписки
    delay_between_batches: 8         # Задержка между пакетами каналов
    delay_retry_wait: 300            # Ожидание перед повтором rate limit (5 минут)
    delay_retry_subscribe: 5         # Задержка после повторной подписки
    delay_between_retries: 8         # Задержка между повторными каналами
    
    # 🚀 НОВЫЕ НАСТРОЙКИ ОПТИМИЗАЦИИ СКОРОСТИ
    fast_start_mode: true            # Быстрый старт (приоритет кешированным каналам)
    skip_new_on_startup: false       # Пропускать новые каналы при запуске

# 🚫 ПРИЧИНЫ ДЛИТЕЛЬНЫХ БЛОКИРОВОК (до 24 часов):
#
# 1. 🔄 Частые перезапуски приложения (НЕ ДЕЛАЙТЕ ЭТО!)
# 2. 📬 Спам рассылки с этого аккаунта  
# 3. 👥 Массовые инвайты в группы
# 4. ⚖️ Нарушения правил Telegram
# 5. ⚡ Слишком быстрая подписка на каналы

# 📝 РЕЖИМЫ РАБОТЫ:
#
# 🚀 ЭКСТРА БЫСТРЫЙ СТАРТ (для продакшена с большим количеством каналов):
# fast_start_mode: true
# skip_new_on_startup: true      # Пропускать новые каналы - только кеш!
# # Результат: запуск за 10-30 секунд вместо 10-30 минут
#
# ⚡ БЫСТРЫЙ СТАРТ (рекомендуется):
# fast_start_mode: true
# skip_new_on_startup: false     # Обрабатывать новые каналы медленно
# # Результат: быстро загружает кеш + медленно обрабатывает новые
#
# 🐌 ОБЫЧНЫЙ РЕЖИМ (для новых систем):
# fast_start_mode: false
# # Результат: все каналы обрабатываются одинаково медленно

# 📝 НАСТРОЙКИ СКОРОСТИ ПО СИТУАЦИЯМ:
#
# 🛡️ БЕЗОПАСНЫЕ (рекомендуется для новых аккаунтов):
# batch_size: 4
# delay_cached_channel: 2
# delay_already_joined: 3
# delay_verification: 4
# delay_after_subscribe: 8
# delay_between_batches: 12
# fast_start_mode: false
#
# ⚖️ СБАЛАНСИРОВАННЫЕ (по умолчанию):
# batch_size: 6
# delay_between_batches: 8
# delay_after_subscribe: 5
# fast_start_mode: true
# skip_new_on_startup: false
#
# 🚀 БЫСТРЫЕ (риск блокировки! для опытных):
# batch_size: 8
# delay_between_batches: 5
# delay_after_subscribe: 3
# fast_start_mode: true
# skip_new_on_startup: true
#
# ⚠️ КРИТИЧЕСКИ ВАЖНО:
# - НЕ перезапускайте бота часто (максимум 1-2 раза в день)
# - При ошибке "wait of 29964 seconds" - просто ЖДИТЕ
# - Используйте "чистые" аккаунты без спам активности
# - При длительной блокировке - смените аккаунт
# - Система автоматически использует кэш для уже подписанных каналов

# 🔍 ДИАГНОСТИКА БЛОКИРОВОК:
# Система теперь автоматически определяет длительные блокировки и выводит:
# "🚫 ДЛИТЕЛЬНАЯ БЛОКИРОВКА: X.X часов" - нужно ждать или менять аккаунт
