


monitoring:
  timeouts:
    
    
    
    batch_size: 6                    
    delay_cached_channel: 1          
    delay_already_joined: 2          
    delay_verification: 3            
    delay_after_subscribe: 5         
    delay_between_batches: 8         
    delay_retry_wait: 300            
    delay_retry_subscribe: 5         
    delay_between_retries: 8         
    
    
    fast_start_mode: true            
    skip_new_on_startup: false       




























































