regions:
  chita:
    channels:
    - title: Канал @chp_chita
      username: chp_chita
    - title: Канал @dtp_chita
      username: dtp_chita
    - title: Канал @chita
      username: chita
    - title: Канал @chita_region75
      username: chita_region75
    - title: Канал @zloykrk
      username: zloykrk
    - title: Канал @chitaru75
      username: chitaru75
    - title: Канал @babr_mash
      username: babr_mash
    - title: Канал @chitamediasu
      username: chitamediasu
    - title: Канал @gtrk75
      username: gtrk75
    - title: Канал @zabchita
      username: zabchita
    - title: Канал @redstonenight
      username: redstonenight
    - title: Канал @gibdd_75
      username: gibdd_75
    name: 🏔️ Чита
  general:
    channels:
    - title: Канал @amur_mash
      username: amur_mash
    - title: Канал @maximum_news
      username: maximum_news
    name: 📰 Общие
  kamchatka:
    channels:
    - title: ИА Кам24
      username: IA_Kam24
    - title: Регион ТВ
      username: regiontv41
    - title: ГИБДД по Камчатскому краю
      username: kamchatkadps
    - title: КБ ГС РАС
      username: kbgsras
    - title: ПКГО
      username: pkgo_official_telegram
    - title: Камчатка Сегодня
      username: kamtoday41
    - title: Правительство Камчатского края
      username: kamgov41
    - title: ГУ МЧС России по Камчатскому краю
      username: mchskam41
    - title: Камчатский край
      username: kam_kray
    - title: Министерство здравоохранения Камчатского края
      username: minzdrav41region
    - title: Госавтоинспекция Камчатского края
      username: gosavtoinspekcia_41
    - title: УМВД России по Камчатскому краю
      username: mvd41
    - title: СУ СК России по Камчатскому краю
      username: suskr41
    - title: ИВС ФЕБРАС КВЕРТ
      username: ivsfebras_kvert
    - title: Министерство образования Камчатского края
      username: MinobrazKK
    - title: Вулканы Камчатки
      username: vulcanikamchatki
    - title: АиФ Камчатка
      username: AiFKamchatka
    - title: Канал @pravonarul
      username: pravonarul
    - title: Канал @melnikov41
      username: melnikov41
    - title: Канал @chpkamchatka
      username: chpkamchatka
    - title: Канал @kamchatinfo
      username: kamchatinfo
    - title: Канал @kamchatkamediaru
      username: kamchatkamediaru
    - title: Канал @massmediakam
      username: massmediakam
    - title: Канал @live_41
      username: live_41
    - title: Канал @newskaminform
      username: newskaminform
    - title: Канал @ukmokrug
      username: ukmokrug
    - title: Канал @bondarenko_ukmo
      username: bondarenko_ukmo
    name: 🌋 Камчатка
  sakhalin:
    channels:
    - title: АСТВ
      username: astv_ru
    - title: Точка 65
      username: tochka_65
    - title: Сахалин Онлайн
      username: sakhonline
    - title: Правительство Сахалинской области
      username: sakhgov
    - title: Южно-Сахалинск
      username: ysakhalinsk
    - title: Мой Корсаков
      username: moykorsakov
    - title: Министерство образования Сахалинской области
      username: sakh_minobr
    - title: Надежда Садина
      username: nadsadin_official
    - title: УГИБДД по Сахалинской области
      username: ugibdd65
    - title: ГУ МЧС России по Сахалинской области
      username: info65mchs
    - title: Канал @incident65
      username: incident65
    - title: СахКо
      username: sakhco
    - title: Канал @mintrans_sakh
      username: mintrans_sakh
    - title: Канал @achs65
      username: achs65
    - title: Канал @minsport65
      username: minsport65
    - title: Канал @sledcomsakhalin_skr65
      username: sledcomsakhalin_skr65
    - title: Канал @mvd_sakh
      username: mvd_sakh
    - title: Канал @minstroy_sakh
      username: minstroy_sakh
    - title: Канал @Prokuratura_Sakhalin
      username: Prokuratura_Sakhalin
    - title: Канал @chpsakhalin
      username: chpsakhalin
    - title: Канал @r2d2sakh
      username: r2d2sakh
    - title: Канал @adm_uglegorsk
      username: adm_uglegorsk
    - title: Канал @crimesakh
      username: crimesakh
    - title: Канал @minenergo_sakh
      username: minenergo_sakh
    - title: Канал @airportus
      username: airportus
    - title: Канал @tsugm
      username: tsugm
    - title: Канал @echosakh
      username: echosakh
    - title: Канал @tugarevAV
      username: tugarevAV
    - title: Канал @sakhalinwatch
      username: sakhalinwatch
    - title: Канал @moy_nevelsk
      username: moy_nevelsk
    - title: Канал @Ist_konst_mayor
      username: Ist_konst_mayor
    - title: Канал @onf_65
      username: onf_65
    - title: Канал @minsotc65
      username: minsotc65
    name: 🏝️ Сахалин
  yakutsk:
    channels:
    - title: Канал @djiikeytop
      username: djiikeytop
    - title: Канал @ysiaru
      username: ysiaru
    - title: Канал @pryanayayakutia
      username: pryanayayakutia
    - title: Канал @novosty_yakutska
      username: novosty_yakutska
    - title: Канал @sakhaday
      username: sakhaday
    - title: Канал @yakutia_kp
      username: yakutia_kp
    - title: Канал @crimyakutiaru
      username: crimyakutiaru
    - title: Канал @yktskandal
      username: yktskandal
    name: ❄️ Якутск
