# 🏢 КАНАЛЫ КОРПОРАТИВНОГО ОТДЕЛА
# Шаблон конфигурации каналов для медиахолдинга
# Настройте каналы для каждого отдела

departments:
  main_department:
    name: "🏢 ${DEPARTMENT_NAME}"        # Название отдела
    channels:
      # 📺 ПРИМЕР: Каналы отдела "Холодное пламя"
      # Замените на реальные каналы вашего отдела
      
      # Основные информационные каналы
      - username: "department_news_1"
        title: "Главные новости отдела"
      
      - username: "department_news_2" 
        title: "Региональные новости"
        
      - username: "department_breaking"
        title: "Срочные новости"
        
      # Специализированные каналы  
      - username: "department_politics"
        title: "Политика"
        
      - username: "department_economics"
        title: "Экономика"
        
      - username: "department_society"
        title: "Общество"
        
      - username: "department_crime"
        title: "Криминал"
        
      - username: "department_emergency"
        title: "ЧП и происшествия"
        
      - username: "department_sports"
        title: "Спорт"
        
      - username: "department_culture"
        title: "Культура"
        
      # Дополнительные каналы (добавьте по необходимости)
      # - username: "department_weather"
      #   title: "Погода"
      
      # Общие каналы медиахолдинга (если нужны)
      # - username: "holding_official"
      #   title: "Официальный канал холдинга"

# 📝 ИНСТРУКЦИИ ПО НАСТРОЙКЕ:
# 1. Замените ${DEPARTMENT_NAME} на реальное название отдела
# 2. Замените username каналов на реальные @username ваших каналов
# 3. Обновите title на соответствующие названия
# 4. Добавьте или удалите каналы по необходимости (9-11 каналов на отдел)
# 5. Сохраните как channels_config.yaml для каждого бота
