alerts:
  enabled: true
  keywords:
    accident:
      emoji: 🚗💥🚑
      priority: true
      words:
      - дтп
      - авария
      - аварии
      - столкновение
      - наезд
      - переворот
      - лобовое
      - пострадавший
      - пострадавшие
      - скорая
      - реанимация
    crime:
      emoji: 🚔⚠️🚨
      priority: true
      words:
      - убийство
      - взрыв
      - стрельба
      - напал
      - ограбление
      - разбой
      - теракт
      - задержан
      - арестован
      - розыск
    disaster:
      emoji: 🌊⚠️🌀
      priority: true
      words:
      - землетрясение
      - цунами
      - наводнение
      - оползень
      - лавина
      - ураган
      - смерч
      - шторм
      - стихия
      - стихийное бедствие
    emergency:
      emoji: 🔥🚨🔥
      priority: true
      words:
      - пожар
      - пожара
      - горит
      - горел
      - горел
      - возгорание
      - огонь
      - дым
      - чс
      - чрезвычайная ситуация
      - эвакуация
      - эвакуируют
    weather:
      emoji: 🌨️❄️⛈️
      priority: false
      words:
      - метель
      - буран
      - снегопад
      - гололед
      - мороз
      - жара
      - град
      - ливень
      - туман
      - шквал
bot:
  chat_id: YOUR_CHAT_ID_FROM_ENV
  token: YOUR_BOT_TOKEN_FROM_ENV
database:
  path: news_monitor.db
logging:
  file: logs/news_monitor.log
  level: INFO
monitoring: null
output:
  target_group: YOUR_TARGET_GROUP_FROM_ENV
  topics:
    chita: 32
    general: null
    kamchatka: 5
    sakhalin: 2
    yakutsk: 890
regions:
  chita:
    created_at: '2025-08-26'
    description: Забайкальский край
    emoji: 🏔️
    keywords:
    - чита
    - chita
    - забайкалье
    - забайкальский
    - краснокаменск
    - борзя
    - петровск-забайкальский
    - нерчинск
    - шилка
    - могоча
    - сретенск
    - хилок
    - '75'
    - '03'
    - забай
    name: 🏔️ Чита
    topic_id: 32
  general:
    created_at: '2025-08-26'
    description: Общие новости и прочие регионы
    emoji: 📰
    keywords: []
    name: 📰 Общие
    topic_id: null
  kamchatka:
    created_at: '2025-08-26'
    description: Камчатский край
    emoji: 🌋
    keywords:
    - камчатка
    - kamchatka
    - петропавловск
    - петропавловский
    - елизово
    - вилючинск
    - усть-камчатск
    - мильково
    - эссо
    - палана
    - оссора
    - '41'
    - kam
    - регион41
    name: 🌋 Камчатка
    topic_id: 5
  sakhalin:
    created_at: '2025-08-26'
    description: Сахалинская область и Курильские острова
    emoji: 🏝️
    keywords:
    - сахалин
    - sakhalin
    - остров
    - южно-сахалинск
    - южно
    - корсаков
    - холмск
    - поронайск
    - углегорск
    - макаров
    - курилы
    - курильские
    - невельск
    - долинск
    - тымовск
    - оха
    - ноглики
    - александровск
    - '65'
    name: 🏝️ Сахалин
    topic_id: 2
  yakutsk:
    created_at: '2025-08-26'
    description: Республика Саха (Якутия)
    emoji: ❄️
    keywords:
    - якутск
    - yakutsk
    - якутия
    - саха
    - yakutia
    - мирный
    - нерюнгри
    - алдан
    - ленск
    - вилюйск
    - олекминск
    - '14'
    name: ❄️ Якутск
    topic_id: null
system:
  cache_size_mb: 100
  max_concurrent_channels: 27
  memory_limit_mb: 800
telegram:
  api_hash: YOUR_API_HASH_FROM_ENV
  api_id: YOUR_API_ID_FROM_ENV
web:
  port: 8080
