telegram:
  api_id: YOUR_API_ID_FROM_ENV
  api_hash: YOUR_API_HASH_FROM_ENV
monitoring: null
bot:
  token: YOUR_BOT_TOKEN_FROM_ENV
  chat_id: YOUR_CHAT_ID_FROM_ENV
output:
  target_group: YOUR_TARGET_GROUP_FROM_ENV
  topics:
    kamchatka: 5
    sakhalin: 2
    chita: 32
    general: null
regions:
  sakhalin:
    name: 🏝️ Сахалин
    emoji: 🏝️
    description: Сахалинская область и Курильские острова
    keywords:
    - сахалин
    - sakhalin
    - остров
    - южно-сахалинск
    - южно
    - корсаков
    - холмск
    - поронайск
    - углегорск
    - макаров
    - курилы
    - курильские
    - невельск
    - долинск
    - тымовск
    - оха
    - ноглики
    - александровск
    - '65'
    topic_id: 2
    created_at: '2025-08-26'
  kamchatka:
    name: 🌋 Камчатка
    emoji: 🌋
    description: Камчатский край
    keywords:
    - камчатка
    - kamchatka
    - петропавловск
    - петропавловский
    - елизово
    - вилючинск
    - усть-камчатск
    - мильково
    - эссо
    - палана
    - оссора
    - '41'
    - kam
    - регион41
    topic_id: 5
    created_at: '2025-08-26'
  chita:
    name: 🏔️ Чита
    emoji: 🏔️
    description: Забайкальский край
    keywords:
    - чита
    - chita
    - забайкалье
    - забайкальский
    - краснокаменск
    - борзя
    - петровск-забайкальский
    - нерчинск
    - шилка
    - могоча
    - сретенск
    - хилок
    - '75'
    - '03'
    - забай
    topic_id: 32
    created_at: '2025-08-26'
  general:
    name: 📰 Общие
    emoji: 📰
    description: Общие новости и прочие регионы
    keywords: []
    topic_id: null
    created_at: '2025-08-26'
  yakutsk:
    name: ❄️ Якутск
    emoji: ❄️
    description: Республика Саха (Якутия)
    keywords:
    - якутск
    - yakutsk
    - якутия
    - саха
    - yakutia
    - мирный
    - нерюнгри
    - алдан
    - ленск
    - вилюйск
    - олекминск
    - '14'
    topic_id: null
    created_at: '2025-08-26'
database:
  path: news_monitor.db
logging:
  level: INFO
  file: logs/news_monitor.log
web:
  port: 8080
alerts:
  enabled: true
  keywords:
    emergency:
      words:
      - пожар
      - пожара
      - горит
      - горел
      - горел
      - возгорание
      - огонь
      - дым
      - чс
      - чрезвычайная ситуация
      - эвакуация
      - эвакуируют
      emoji: 🔥🚨🔥
      priority: true
    accident:
      words:
      - дтп
      - авария
      - аварии
      - столкновение
      - наезд
      - переворот
      - лобовое
      - пострадавший
      - пострадавшие
      - скорая
      - реанимация
      emoji: 🚗💥🚑
      priority: true
    disaster:
      words:
      - землетрясение
      - цунами
      - наводнение
      - оползень
      - лавина
      - ураган
      - смерч
      - шторм
      - стихия
      - стихийное бедствие
      emoji: 🌊⚠️🌀
      priority: true
    crime:
      words:
      - убийство
      - взрыв
      - стрельба
      - напал
      - ограбление
      - разбой
      - теракт
      - задержан
      - арестован
      - розыск
      emoji: 🚔⚠️🚨
      priority: true
    weather:
      words:
      - метель
      - буран
      - снегопад
      - гололед
      - мороз
      - жара
      - град
      - ливень
      - туман
      - шквал
      emoji: 🌨️❄️⛈️
      priority: false
system:
  memory_limit_mb: 800
  max_concurrent_channels: 27
  cache_size_mb: 100
