# 🏢 КОРПОРАТИВНАЯ КОНФИГУРАЦИЯ МЕДИАХОЛДИНГА
# Шаблон для настройки отдельного отдела
# Скопируйте этот файл в config.yaml для каждого бота

# 📱 Telegram API (уникальные для каждого отдела)
telegram:
  api_id: "${TELEGRAM_API_ID}"           # Из my.telegram.org для этого отдела
  api_hash: "${TELEGRAM_API_HASH}"       # Уникальный для каждого аккаунта

# 🤖 Настройки бота (уникальные)
bot:
  token: "${BOT_TOKEN}"                  # Токен бота от @BotFather
  chat_id: "${BOT_CHAT_ID}"              # ID админа отдела

# 📤 Целевая группа публикации (уникальная)
output:
  target_group: "${TARGET_GROUP_ID}"     # ID группы отдела для публикации новостей
  excluded_topics: [26, 27]             # Темы для исключения (флуд, оффтоп)
  
  # 📂 Маршрутизация по темам отдела
  topics:
    department_main: null               # Основная лента отдела
    department_urgent: 2                # Срочные новости
    department_analytics: 5             # Аналитика
    department_events: 8                # События

# 🏢 Отделы вместо регионов
departments:
  main_department:
    name: "🏢 ${DEPARTMENT_NAME}"        # Например: "🔥 Холодное пламя"
    emoji: "${DEPARTMENT_EMOJI}"         # Уникальный эмодзи отдела
    description: "Отдел ${DEPARTMENT_NAME} медиахолдинга"
    keywords: []                         # Ключевые слова для автоопределения (если нужно)
    topic_id: null                       # ID топика для этого отдела
    created_at: "2025-01-24"

# 🚨 Система алертов (общая для всех отделов)
alerts:
  enabled: true
  keywords:
    emergency:
      emoji: "🔴🚨"
      priority: true
      words: ["пожар", "взрыв", "чс", "авария", "дтп", "теракт"]
    important:
      emoji: "🟡⚠️"
      priority: false
      words: ["власть", "суд", "прокуратура", "следствие", "арест"]
    corporate:
      emoji: "🏢📢"
      priority: false
      words: ["медиахолдинг", "редакция", "журналист", "СМИ"]

# ⚙️ Мониторинг (безопасные настройки для корпоративного использования)
monitoring:
  timeouts:
    batch_size: 4                       # Консервативно: 4 канала в пакете
    delay_cached_channel: 2             # 2 сек между кешированными каналами
    delay_between_batches: 10           # 10 сек между пакетами (безопасно)
    delay_retry_wait: 600               # 10 мин ожидание при rate limit
    fast_start_mode: true               # Быстрый старт с кешем

# 💾 База данных (настраивается через переменные окружения)
database:
  path: null  # Путь устанавливается автоматически через DATA_PATH

# 📝 Логи (настраиваются через переменные окружения) 
logging:
  file: null  # Путь устанавливается автоматически через LOG_PATH
  level: INFO

# 🖥️ Системные ресурсы (для мощного сервера)
system:
  max_concurrent_channels: 50           # Больше каналов на мощном сервере
  memory_limit_mb: 1024                 # 1GB на отдел
  cache_size_mb: 200                    # 200MB кеша на отдел
